name: Cypress Tests UI Run on Pipeline

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: failure()
        with:
          name: cypress-snapshots
          path: cypress/snapshots
      - run: npm i
      - name: 'Run Cypress tests'
        run: npx cypress run
      # - store_artifacts:
      #   path: cypress\screenshots